ocpi/ocpi

- releases/OCPI-Draftv3.md
This is a version from may, 6th 2014. It's included as a separate file because the repo history doesn't go back that far.
> upload draft v3 for reference purposes

- template-object-description.md
This is based on the discussions in Meeting #13 
It can be used to create the files to describe individual objects. We should agree on this structure before we start adding data.
> Added a template for object descriptions

- transport_and_format.md
> Fixed typos in transport_and_formats.md

- mod_cdrs.md
Connector standard should have underscores
> Sample JSON has invalid connector-type

- mod_tokens.md
Some minor language related fixes.
> Fix spelling/language errors

- mod_cdrs.md
- mod_tokens.md
- smart_charging.md
- terminology.md
I'm happy to provide these textual improvements through a pull request. I don't require attribution or anything, just wanted to help out as a person who cares about a sustainable and smooth EV future.
Feel free to decide to cherry pick individual commits instead if you prefer to adopt only certain changes.
> Fixes a few bits of text

- transport_and_format.md
As discussed in https://github.com/ocpi/ocpi/issues/148
> Respond with 401 - Unauthorized to unknown token

- mod_locations.md
as discussed in the OCPI slack group
> remove 'choice' for Hours type

- introduction.md
also add note about possibly breaking change
> fix minor errors in chapter 1.1.1

- mod_tariffs.md
Pls see https://github.com/ocpi/ocpi/issues/237
> Fix example regex for TariffRestrictions#start_time

- mod_charging_profiles.asciidoc
> Fix typo: Charging Profile module ID

- mod_locations.asciidoc
> Fixing typo 'visual_number'

- mod_locations.asciidoc
Changed known to know in section 8.1.2 and limit to limited in section 8.3.1.4
> Fixed typo in mod_locations.asciidoc

- CONTRIBUTING.md
Trying again.  I'm sorry this is taking forever for me to get right.
> Typos and adding to the Pull Request Process

- credentials.asciidoc
- mod_hub_client_info.asciidoc
- mod_locations.asciidoc
- mod_sessions.asciidoc
- terminology.asciidoc
- types.asciidoc
- version_information_endpoint.asciidoc
I've been making small changes to punctuation (adding periods [.] to some of the lists) and some wording changes as I come across them.  I'll keep doing this as I work my way through the document.  Please only accept the changes that you feel are appropriate.
> Punctuation and wording

- terminology.asciidoc
This is not consistent with paragraph 4.1.7.2
> Fixed inconsistency with Message Routing Header paragraph

- transport_and_format.asciidoc
> 2.2 client owned objects

- mod_locations.asciidoc
Added a period to the end of the sentence
"This field may only be used when the `publish` field is set to `false`."
> Punctuation

- mod_cdrs.asciidoc
- mod_charging_profiles.asciidoc
- mod_commands.asciidoc
- mod_hub_client_info.asciidoc
- mod_sessions.asciidoc
- mod_tariffs.asciidoc
- mod_tokens.asciidoc
- transport_and_format.asciidoc
Just updating a number of minor things that I've noticed over the months.
> Fixing a bunch of typos, grammar, and punctuation.

- mod_tariffs.asciidoc
Have I done this right?  I'm trying to change "shall" to "SHALL" in a couple places.
> Alan stewart patch 3
