ocpi/ocpi

OCPI.md
it's (ALPHA | DIGIT | \<S\> ), not (ALPHA | DIGIT \<S\> )
=> added disjunction operator to power outlet ID

mod_tariffs.md
Parameter "type" in "price_components" should be upper case, as it is defined in the DimensionType enum  (see https://github.com/ocpi/ocpi/blob/master/types.md#14-dimensiontype-enum )
=> Fixed some typos

credentials.md
This pull request fixes the Credentials example in credentials.md in which field 'logo' was not according to the defined type 'BusinessDetails' in mod_locations_and_evses.md.
=> Conform 'logo' in example to defined type. Fixes #63.

mod_cdrs.md
Use integers to represent
'location.evse.connectors.voltage' & 'location.evse.connectors.amperage'
as defined in Connector type
Use decimal to represent 'volume' in
'charging_periods.dimensions' & 'total_usage'
as defined in CdrDimension type
----
*Side note* 
In 'total_usage', elements are defined as array items, which allows for repetition of same type elements. There is no comment on reasoning behind this and how anybody should interpret such cases. It may be valuable to turn 'total_usage' from array to object with dimension type being key and 'volume' with 'step_size' being values. For example instead of 
```
"total_usage": [{
"type": "TIME",
"volume": "1.973"
}, {
"type": "ENERGY",
"volume": "15.342"
}]
```
use 
```
"total_usage": {
"TIME": {
"volume": "1.973"
}, 
"ENERGY": { …
```
=> Align CDR example with type description

mod_tokens.md, transport_and_format.md
This is a critical bug because it describes that the URL of a PUT request (something that the eMSP does) must contain the CPO's country_code and the CPO's party_id when it should be the eMSP's country_code and party_id respectively.
=> Reverse CPO and eMSP parameters in the Token's PUT request URL

credentials.md
Clearly explain server side behaviour (such as token generation) per method. GET should not reference POST or PUT as it breaks the top-to-bottom reading flow.
=> OCPI 2.1 RC1 rework: Fixed issue 14

mod_commands.md, mod_locations.md
To be able to use the protocol via a roaming platform, the `evse_uid`
should be the EVSE-ID as specified by eMI3. Therefor it has to be able
to contain a 48 character string.
=> Extending `evse_uid` to string(48) match EVSE-IDs

credentials.md
Because using 'credentials for X' could mean:
- credentials that X needs to access your system
- credentials that you need to access X's system
So this is a fix to clarify that.
=> Clarify whose credentials we are sending

mod_commands.md
Looking at the spec I see that the StopSession object needs a session ID, which the MSP can only receive and subsequently supply by implementing the MSP interface of the Session module.
=> update list of deps for mod_commands

mod_cdrs.md, mod_locations.md, mod_sessions.md
Some of the examples used to explain the definitions of eg. Location or EVSE objects have some incorrect information (= not in line with the standard). I have located these them in the examples.  As suggested in #157, I have fixed these and created this pull request.
Some issues:
- Incorrect number of decimals (more than standard 4)
- Incorrect longitude or latitude (too few decimals according to regex definition)
- Keys in uppercase (all keys are defined in lowercase)
- Enum values in lowercase (all defined in uppercase)
- Incorrect keys used
- Use of non-UTC timestamps
=> Fix examples to be in line with the standard

transport_and_format.md
There is no `allow_whitelist` property. A [Token Object](https://github.com/ocpi/ocpi/blob/master/mod_tokens.md#32-token-object) has a `whitelist` property though.
Additionally the mandatory `last_updated` property was missing.
=> Update Tokens Endpoint examples to be in line with the Tokens Endpoint Spec

credentials.md
The description for the `url` field in a `Credentials` object reads _“The URL to your API versions endpoint.”_
The contained example following it shows `https://example.com/ocpi/cpo/` as a value for the `url` field.
When checking the documentation on the Versions Endpoint, it is always mounted on `https://…/versions`. This change updates the value of `url` to be in line to that part of the documentation.
=> Update `url` in Credentials Object Example to match spec

mod_sessions.md
I think there's an error in the "Simple Session example of a short finished session" on the sessions doc (https://github.com/ocpi/ocpi/blob/master/mod_sessions.md#31-session-object).
The "status" key in the EVSE object should be lowercase.
=> EVSE's object "status" key in example should be lowercase

mod_commands.md
I think there's an error on the current request body and response body for the POST, which should be of type CommandResponse (an object like `{"result": "ACCEPTED"}` instead of type CommandResponseType, which is a simple string.
=> Command POST request and response should be CommandResponse type

mod_locations.md
The example for energy_sources is not valid JSON as it contains some trailing commas. This PR removes those trailing commas.
=> Fix `energy_sources` example

mod_hub_client_info.asciidoc
This PR fixes a minor spelling mistake of the `RoleType` enum.
As the whole `HubClientInfo` module has been added with v2.2 and there has been no final release of this version yet, it should be no issue changing the spec.
=> Fix spelling mistake in RoleType enum

credentials.asciidoc, mod_cdrs.asciidoc, mod_charging_profiles.asciidoc, mod_hub_client_info.asciidoc, mod_locations.asciidoc, mod_sessions.asciidoc, mod_tariffs.asciidoc, mod_tokens.asciidoc, status_codes.asciidoc, transport_and_format.asciidoc, version_information_endpoint.asciidoc
I started going through the documentation of OCPI 2.2-rc1 and fixed some of the spelling/wording issues I found. I also highlighted some occurences of `should`, `may` or `must` by writing them entirely uppercase where I found them to be important.
Before going further with this, are such contributions actually desired?
I realize that not all of my changes are _very minor spelling/wording alternations_. For example, in `credentials.asciidoc` I added `ISO-3166 alpha-2` as source for country codes as it seems the only logical source to me. One could see this as unwanted constraint, I see it as suggestion of good practice. Therefore I'd appreciate some feedback before going on with what I'm doing so far.
=> A few documentation improvements

examples/tariff_18_reservation_with_expire_time.json, examples/tariff_3_alt_url.json, examples/tariff_6_025kwh_start_max_price.json, mod_tariffs.asciidoc
This PR only touches the `mod_tariffs.asciidoc` file and related examples. It improves the wording and spelling and unifies the styling of things.
A big part of this PR is also an extension of the tariff examples by an explanation of each example. It was sometimes difficult to understand the pricing logic, which makes this even more valuable in my opinion.
Please have a (thorough) look at this @RobertdeLeeuw-IHomer, @poohsen as there might be understanding issues in the examples.
=> OCPI 2.2: Improve Tariff Descriptions

examples/tariff_4_complex.json
Fixes complex tariff example.
Min and max power (kW) restrictions changed to current (A)
=> fix: complex tariff min and max power to current

examples/tariff_15_reservation_5_euro_per_hour.json, examples/tariff_16_reservation_2_euro_fee_5_euro_per_hour.json
The tariffs "tariff with reservation price" and "tariff with reservation price and fee" have a price of 5€ per hour but the examples have 6€.
=> Incorrect prices for tariff with reservation price

C_transport_modules/changelog.asciidoc, C_transport_modules/mod_cdrs.asciidoc
This is to aid the customer in matching a CDR to their recollection of charging activity.
=> add evse_physical_reference to CdrLocation

examples/session_example_1_simple_start.json, examples/session_example_2_short_finished.json
This file contained a mistake because it wasn't updated to the OCPI version 2.2 with a CdrToken object nested under the key `cdr_token` in the session JSON. 
This was proposed on Slack here: https://ocpi.slack.com/archives/C0S64NZJQ/p1583748925005100
=> Makes this example conform to OCPI v 2.2

changelog.asciidoc, examples/location_example.json, examples/location_put_example_add_evse.json
`tariff_id` should be `tariff_ids` and of type `array` on `connector`.
=> Fix typos in location examples

examples/cdr_example.json
Tariff inside the CDR example should contain the fields country_code and party_id to adhere to the spec.
=> Tariff should contain country_code and party_id

examples/token_put_example.json
This PR adjusts the `country_code` in the Tokens PUT Example so that it matches the `country_code` in the URL being used. This to comply with the spec's prescription that these two SHALL be the same value.
=> Update Tokens Put Example. Fix #312

examples/cdr_example.json
The documentation states, the CDRLocation Object has only singular key names.
=> fixed plural typo in cdr_example.json

credentials.asciidoc, transport_and_format.asciidoc
We saw some confusion on Slack regarding the use of base64 encoding in the `Authorization` header of OCPI requests. This relates to earlier confusion expressed in #212 . This pull request aims to make the specification completely clear and consistent about this.
=> clarify use of base64 in HTTP auth header

mod_tariffs.asciidoc
Tariff example uses ampere for power instead of current
=> Changed power to current for amperes

types.asciidoc
Currently, the type role looks like a sub-element of price, which at least for me looks pretty wrong; it should be a level up, so is not a child of Price class.
Currently:
* 16.5. Price class
* 16.5.1. Role enum
...
In my opinion, it should be:
* 16.5. Price class
* 16.6. Role enum
...
=> Fix level of Roles in Types

mod_tokens.asciidoc
The reference is targeting the wrong file, in that reference does not exist in types, exists in mod_tokens
=> Fix link to anchor, to #mod_tokens_energy_contract
